[tox]
envlist = py310, py311, py312
minversion = 4.0
skipsdist = true

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
deps =
    poetry
    packaging==23.2
commands =
    poetry install --no-root
    poetry run pytest \
        --cov=gpt_computer \
        --cov-report=xml \
        --cov-report=html \
        --cov-report=term-missing \
        --cov-branch \
        --junitxml=junit-{env}-results.xml \
        -k 'not installed_main_execution' \
        {posargs}
passenv = OPENAI_API_KEY,ANTHROPIC_API_KEY,GROQ_API_KEY

[testenv:coverage]
skip_install = true
deps =
    {[testenv]deps}
    coverage[toml]
commands =
    poetry run coverage run -m pytest -k 'not installed_main_execution'
    poetry run coverage report -m
    poetry run coverage html
    poetry run coverage xml

[testenv:lint]
skip_install = true
commands =
    poetry run ruff check gpt_computer tests
    poetry run mypy gpt_computer --ignore-missing-imports
    poetry run black --check gpt_computer tests

[testenv:format]
skip_install = true
commands =
    poetry run black gpt_computer tests
    poetry run ruff check --fix gpt_computer tests

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
